MEN-4180: improve onboarding tooltips visibility
mendersoftware/gui pull request #1183
Opened 2021-01-05 09:39 UTC by tranchitella

2021-01-05 15:02 UTC, mzedel requested changes
👍 nicely done, the fallback approach is just what I had in mind! if I remember correctly there were a few more steps that served as an anchor though (or we will have to reopen the issue very soon)...

2021-01-05 16:16 UTC, tranchitella commented on src/js/actions/onboardingActions.js
> +    const progress = applyOnboardingFallbacks(onboardingState.progress) || determineProgress(acceptedDevices, pendingDevices, releases, pastDeployments);
Ack

2021-01-13 06:06 UTC, tranchitella commented
@mzedel ready for review; I've incorporated your changes to the fallback, but also added three commits (you can review them, specifically) to streamline the onboarding tips. It works well here, now. No more spurious welcomeTip at application startup, which was annoying me so much.

2021-01-13 09:38 UTC, mzedel approved these changes
Thank you very much for the fixes! 🎉 especially for the welcometip!

2021-01-13 09:40 UTC, mzedel commented
merging to get this straight to staging...

2021-01-13 09:40 UTC, merged