MEN-4178 help & docs reference adjustments
mendersoftware/gui pull request #1246
Opened 2021-01-20 23:59 UTC by mzedel

2021-01-29 16:50 UTC, michaelatmender commented on src/js/components/common/dialogs/__snapshots__/virtualdeviceonboarding.test.js.snap
> +      href="https://docs.mender.io/development/get-started/preparation/prepare-a-virtual-device"
I'd make this target="_blank" too

2021-01-29 16:55 UTC, michaelatmender commented on src/js/components/common/dialogs/__snapshots__/deviceconnectiondialog.test.js.snap
> +                  The steps in the guide should work on most operating systems in the debian family (e.g. Debian, Ubuntu, Raspberry Pi OS) and devices based on ARMv6 or newer (e.g. Raspberry Pi 2/3/4
'debian family' should be 'Debian family', it's been the incorrect case for a while!

2021-01-29 16:59 UTC, michaelatmender requested changes
Just two tiny changes requested, otherwise looks good!

2021-01-29 18:58 UTC, estenberg commented
Great improvement!

It is a bit hard to visualize how it will look based on the code but the changes look good to me and can take a look at the Help section once merged to see if there are any minor changes I'd suggest at that point too :+1:

2021-01-29 18:58 UTC, estenberg approved these changes

2021-02-01 10:24 UTC, michaelatmender approved these changes

2021-02-01 10:54 UTC, merged