brought back click-to-copy on device attributes
mendersoftware/gui pull request #1403
Opened 2021-03-24 10:29 UTC by mzedel

Changelog: None
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

2021-03-24 11:00 UTC, michaelatmender requested changes
This works fine, but it is a bit hidden now. Could you add in the copy icon when the user hovers on a row too? (if it requires the rows to have a little more space between them, that's ok)
![hovercopy](https://user-images.githubusercontent.com/15045782/112299711-58f06800-8c98-11eb-8fee-1ee2afb13c70.jpg)

2021-03-24 12:16 UTC, mzedel commented
thanks @michaelatmender! should now be very close - I kept it triggering on the value part only though (as I would expect the row to include both key & value as they are now almost equally prominent)...

2021-03-24 12:18 UTC, oleorhagen reviewed
:eyes: 
This javascript is some 20 years to modern for my liking

2021-03-25 08:07 UTC, michaelatmender approved these changes

2021-03-25 09:05 UTC, merged