WIP mui theme dark & 3rd party
mendersoftware/gui pull request #2375
Opened 2022-01-13 11:27 UTC by Jackbennett

Hi, I've updated the frontend to use the currently set theme on the ThemeProvider framework. This still needs work but 

Tasks involved:
- [x] Migrate `mender-theme.js` into a MUI light/dark
- [x] Remove `theme` access from outside `useTheme`
- [ ] Remove `colors` access from outside `useTheme` either `theme.pallete` or custom `theme.colors`
- [ ] Remove chartColorPalette for a mechanism from `useTheme` `theme.*`
- [ ] Somehow coordinate colors from `variables.less` into  design tokens used within the mui theme. 
- [ ] Create interface to theme switching mechanism
- [ ] Format commits in line with contributors guide.

I made the changes from 3.1.0 but rebased onto master. I think I've kept the right changes to templates.

## uniting `*.less` and material theme
Two ways I'm not a huge fan of might be;
* Remove all less in flavor of style components - Could be lots of work
* Remove all the colours from less, instead changing components to use material styles - probably difficult given the specificity in less

What I'm learning towards at the moment might look like mapping material design tokens into less.
1. Add the tokens into variables.less,
2. Change existing variables to refer to those tokens
3. Update mui to pull the theme values from that less token map
4. Gradually over time change UI into styled components to use the mui tokens directly instead of less. Possibly after moving to bootstrap5 to avoid adding and jss

## Concerns
* Want to avoid writing a bunch more styled components if that's all going to need changing again from Material v4 -> v5
* Light should look exactly the same as it does now. This isn't a rebrand.

## Related Discussions;
- Initial request; https://hub.mender.io/t/switchable-gui-material-theme/4471/4

# Previews
![image](https://user-images.githubusercontent.com/791134/149321745-081f073f-21c7-478f-aa9f-8087dbba843c.png)
Current biggest issue with this being the greyscale used from less instead of `theme.palette.grey[x]`

2022-01-13 16:10 UTC, mzedel requested changes
Thank you very much for the PR - that is quite a bit!

To continue on this I think targeting the feature branch would be best + considering the additional things to do it might be helpful to first do a _rough_ MUI upgrade and rebase this PR on that... What do you think @Jackbennett?

2022-01-13 16:31 UTC, Jackbennett commented on docker-compose.yml
> +volumes:
Ah yeh anything to do with docker I should drop in a rebase that's just my dev setup has snuck in there sorry.

2022-01-14 09:41 UTC, Jackbennett commented
> To continue on this I think targeting the feature branch would be best + considering the additional things to do it might be helpful to first do a _rough_ MUI upgrade and rebase this PR on that... What do you think @Jackbennett?

I'm unsure as to how much churn you want into releases but happy to follow what make sense for you.

I'm focusing on linking up the context that mui and `less` effect so it should get easier and easier to push things into mui styled components. With regards to actual colors and styling no doubt that's up to yourselves internally what/if you want a dark theme to look like. I'm just getting the supports in place for themes in general.  You might choose to put the manager behind a plan addon, I won't write a manager I can edit the self-hosted service.

I have a question though, is all of the frontend code here? You don't have another enterprise source? Tracking down where some of the less is used there's some dead ends that could be removed.

Personally I haven't used material v5 yet only v4 but happy to get stuck in.

2022-01-14 15:54 UTC, Jackbennett commented on Dockerfile
> +FROM nginx:1.21.5-alpine as Server
I toyed around with the entrypoint but didn't seem to need it. Not for dev, that env.js being written in there makes things a bit complicated. Docker stuff is outside the scope anyhow so I've rebased it out.

2022-01-14 15:56 UTC, Jackbennett commented on src/js/components/devices/device-details/notifications.js
> +  [monitoringSeverities.CRITICAL]: { className: 'red', icon: errorIcon },
Fixed, spoiled by typescript didn't even read that was an export sorry.

2022-01-14 16:47 UTC, Jackbennett commented
This is possibly in a good spot to update to mui v5 to start stripping colours from main.less and stop using `import { colors }`

mui can get the theme from `<Box sx={background-color: theme => theme.palette.grey[200]}} />` which would probably remove 80% of the `import { useTheme } ... const theme = useTheme()` I just added.

I don't think I'm going to pick this up for another week which sounds like nice timing while you had this scheduled. I'm not sure if a small update first would make this easier, other than getting the component interfaces out there. It would introduce a short time to notice regressions from the UI that hasn't changed in a year (guessing from commit dates i saw while editing) a 3.x with small changes and 3.x+1 on mui-v5

2022-01-25 11:44 UTC, mzedel requested changes
Thanks once again for the continued changes! I progressed a bit with the upgrade to mui5, however the changes to the components (alone the imports e.g.), test files and theme structure are a lot...
In order to streamline the adjustments I would thus like to merge your PR in the feature branch, get the rough mui upgrade in there (after I rebased again with your changes merged) as well and then from there get rid of the remaining inconsistencies in the theme... would that work for you?

2022-01-25 11:44 UTC, mzedel commented on src/js/components/artifacts/releaseslist.js
> +    <ListItem button selected={isSelected} className={['repository-list-item']} onClick={() => onSelect(release)} style={style}>
that should most likely be a simple string

2022-01-25 11:44 UTC, mzedel commented on src/js/components/deployments/deployment-wizard/softwaredevices.js
> +}
that omission will be flagged by the prettier checks

2022-01-25 11:44 UTC, mzedel commented on src/js/components/deployments/deployment-wizard/softwaredevices.js
>    },
that comma will be flagged by the prettier checks

2022-01-25 17:32 UTC, Jackbennett commented
I had some fixes still on here to push in for what you mentioned.

I also found to write the theme into css variables from mui for less to pick back up as an interim to getting it rebuilt. I'm swapping between light/dark/custom to find elements that are missing when considering styling.

There's a lot that will change with the v5 and updating tests, I think what you propose sounds like the best way to handle that. To take advantage of v5 there's component changes and some stylistic choices I don't think I can make as an outsider. That pink in `tooltipText` I'm not sure about for example.

Sorry about the lint changes creeping in I've got the code in  a container but not VSCode so from its point of view it's not installed.

2022-01-25 18:05 UTC, mzedel commented
Nice solution with the css variables, based on their availability and the general reduction of less dependency in the codebase that might be a good way to _some day_ get rid of it entirely (and speed up the build setup)...
Regarding the theme I will also gladly keep this for a colleague to tune as I tend to get lost in the code to the detriment of the design 🙈.
And don't worry about the lint changes - with the mui upgrade applied, there are worse tests to fix (besides the pending theme alignment).

If you're ok with where things stand feel free to mark this as ready for review, I'll merge to the feature branch and ready the  PR for the upgrade (the rebase is probably going to be interesting)...

2022-01-26 09:49 UTC, Jackbennett commented
Thanks for your collaboration it helped clear a lot up :)

Some notes;

* You might not want to keep `theme.palette.qualitative` for chart colors
* Seems like CSS variables don't go into less functions life `fade` but there's alternates. Also consider just using the `.light` `.dark` variants along side `.main` that mui provides
* `import { colors } ...` is the next major thing to get rid of
* I think MUIv5 using function in `sx=` could remove most useTheme calls.
* I used this to harmonise the greyscale https://vis4.net/palettes/#/11|d|969696,aaaaaa,c7c7c7,f7f7f7|eaf4f3,d4e9e7|1|1 then took out one of the lighter stops that was low contrast

Hope it all helped.

2022-01-26 10:01 UTC, mzedel commented
Alright, I'll keep that list prominent and will forward the palettes tip! I'll try to make this land in master asap and will ping here once there is a docker image pushed that you could use - if you don't use a self built one anyway of course.

There is however one last thing that you need to do (for legal reasons for us): adding a signoff to all your commits (& preferably also a last rebase onto the target branch - but at least that I could take care of if you don't want to)...

2022-01-26 10:13 UTC, mzedel commented
Great, that last push fixed all commits except for the last one (dd645e5c6000e66d9d860fb6ccae2ecddb0c6609), where `Author: Jackben <j.bennett@engineeredarts.co.uk>` and `Signed-off-by: Jackbennett <code@jackben.net>` conflict - that `test:check-commits` stage in the pipeline is the only that needs to pass for now...

2022-01-26 10:18 UTC, Jackbennett commented
Ok CI is happy with eslint fixed and commits with signoff and changelog I'll leave this alone now :+1:

2022-01-26 10:24 UTC, mzedel approved these changes

2022-01-26 10:29 UTC, merged