MEN-5453
mendersoftware/gui pull request #2934
Opened 2022-07-20 20:11 UTC by mzedel

2022-07-22 11:04 UTC, tranchitella requested changes

2022-07-22 11:04 UTC, tranchitella commented on src/js/components/settings/integrations.js
> +  amazon: ConnectionDetailsInput,
This should be iot-core

2022-07-26 08:51 UTC, tranchitella commented
@mzedel still not working as expected, the UI is sending:
`{"provider":"amazon","credentials":{"type":"aws","access_key_id":"A","secret_access_key":"B","endpoint_url":"https://mender-test-hub.azure-devices.net","device_policy_ARN":"C"}}`

It should send:
`{"provider":"iot-hub","credentials":{"type":"aws","access_key_id":"A","secret_access_key":"B","endpoint_url":"https://mender-test-hub.azure-devices.net","device_policy_ARN":"C"}}`, instead.

2022-07-26 11:39 UTC, mzedel commented
@tranchitella can you double check you tried it with the latest version? there should not be any trace of `amazon` in the src folder any more...

2022-07-26 11:51 UTC, tranchitella commented
@mzedel I'm sorry, I messed up my local branch, you are right. I still have an issue, though: despite correct data being returned by the end-point, the UI is not populating the fields with the existing values:

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/1295287/180999285-c0c9cd7e-fa65-4d0a-8243-8730a44dc897.png">

Any idea why this is happening?

2022-07-26 12:27 UTC, mzedel commented
@tranchitella yes you're right - the config destructuring and the casing for the config were not aligned with the endpoint - should now be aligned... I also added a simple URL validation for the endpoint, unfortunately it won't catch non-trusted domains (btw thanks a lot for the example data!)...

2022-07-27 05:32 UTC, tranchitella approved these changes

2022-07-27 07:29 UTC, merged