MEN-5103 - SSO setup
mendersoftware/gui pull request #2989
Opened 2022-08-01 16:28 UTC by mzedel

2022-08-03 05:02 UTC, tranchitella requested changes
I have a suggestion: when setting up the Service Provider application in your IdP, you need to specify two values:
- ACS URL
- Entity ID

Additionally, to log in to Mender, you need to know the SSO login URL, e.g. https://docker.mender.io/api/management/v1/useradm/auth/sso/UUID/login

See screenshot (from the Google admin console):
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/1295287/182527744-ad9c7aa8-17f1-4a42-bbd7-04042f5f990e.png">

Would it be possible to expose these URLs/values in easy-to-copy-to-the-clipboard text fields?

2022-08-03 13:05 UTC, mzedel commented
@tranchitella like so?

<img width="796" alt="Screenshot 2022-08-03 at 15 03 01" src="https://user-images.githubusercontent.com/482243/182614779-5e285776-8e6d-44d1-a1e2-73f17cba56a7.png">

unless @michaelatmender objects of course!

2022-08-04 07:57 UTC, tranchitella approved these changes
It looks good, I only have three extra requests:
- Remove the double slash from the URLs
- Order as follows: Entity ID, ACS URL, login URL
- Rename "Start URL" to "Login URL"

2022-08-04 08:53 UTC, tranchitella approved these changes

2022-08-05 20:58 UTC, merged