MEN-5516 - WIP
mendersoftware/gui pull request #2994
Opened 2022-08-03 13:18 UTC by mzedel

2022-08-19 06:46 UTC, mzedel commented
@michaelatmender now this should be ready for a last review round and I don't expect more rebases/ changes to the existing commits to come in the next few days 👌

2022-08-22 14:17 UTC, michaelatmender requested changes
I only found one small thing left to adjust that affected the light theme

2022-08-22 14:17 UTC, michaelatmender commented on src/js/themes/Mender/light.js
> +    primary: 'rgba(10, 10, 11, 0.78)'
a `text.hint` value of something like `rgba(0, 0, 0, 0.5)` is needed here to ensure the "connector" arrow lines are visible in the update pauses step when creating a deployment. It's also used to give the device list header text a lighter color

2022-08-23 09:27 UTC, michaelatmender approved these changes

2022-08-23 09:29 UTC, merged