MEN-5647 - deployment creation sliding in
mendersoftware/gui pull request #3030
Opened 2022-08-25 08:24 UTC by mzedel

2022-08-29 08:29 UTC, tranchitella commented
It behaves in a strange way with the links to the "features page", see screenshot:

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/1295287/187158734-7e33f593-f88f-402e-b389-8dca983b9475.png">

2022-08-29 08:32 UTC, tranchitella commented
Also, after I create a deployment, if I try creating a new one (open source flavour) the button "CREATE DEPLOYMENT" stays disabled despite the selection of the group (All devices) and the artifact. A full refresh fixes it, it must be something in the state.

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/1295287/187159290-2781b7dc-252a-4f20-9ef3-f8825648f23b.png">

2022-08-29 11:59 UTC, mzedel commented
Thanks @tranchitella for taking a look!

> It behaves in a strange way with the links to the "features page"

should be adressed with https://github.com/mendersoftware/gui/pull/3030/commits/72c5554fefd924be457ec8692a429b89029e9375

whereas:

> ... creating a new one (open source flavour) the button "CREATE DEPLOYMENT" stays disabled despite the selection of the group (All devices) and the artifact ...

should be addressed with [this change](https://github.com/mendersoftware/gui/compare/f340e3c8c31922721b257a62dce927ad25f446c5..72c5554fefd924be457ec8692a429b89029e9375#diff-47a71389c5ea3672d7716404673e07f06a41b4e96662a85210744a253efb8a08R192) to the multiple-deployment-creation-prevention-mechanism™️

2022-08-29 12:31 UTC, michaelatmender commented on src/js/components/deployments/createdeployment.js
> +      <div className="flexbox margin-bottom space-between center-aligned">
I think "margin-bottom" is not needed here

2022-08-29 12:40 UTC, michaelatmender requested changes
Just two small things I noticed: 

1. The header margin I left a comment on,
2. The 'retry' dropdown should be updated to match the new label text. It's no longer 'number of retries', but total number of attempts - so it should start at "1" by default This is to make it consistent with the rest of the UI

2022-08-29 15:02 UTC, mzedel commented
> 1. The header margin I left a comment on,
> 2. The 'retry' dropdown should be updated to match the new label text. It's no longer 'number of retries', but total number of attempts - so it should start at "1" by default This is to make it consistent with the rest of the UI

Thanks @michaelatmender - these should now be adjusted 👌!

2022-08-30 05:30 UTC, tranchitella approved these changes
It looks good now, thank you @mzedel!

2022-08-30 06:25 UTC, merged