MEN-7029: Download log button failing to download file
mendersoftware/gui pull request #4348
Opened 2024-03-04 09:35 UTC by mineralsfree

Previous implementation didn't send authorization header 

Ticket: MEN-7029
Changelog: None

2024-03-04 11:11 UTC, aleksandrychev commented
@mineralsfree this change doesn't look like a proper fix. what's wrong here, when you click a log link then API endpoint authorization does not happen?

2024-03-04 11:13 UTC, mineralsfree commented
> @mineralsfree this change doesn't look like a proper fix. what's wrong here, when you click the log link then API endpoint authorization does not happen?

It opens a link in a new tab trying to fetch a file, but since JWT token is not passed in HTTP header, the request is not authorized

2024-03-04 11:18 UTC, aleksandrychev commented
> > @mineralsfree this change doesn't look like a proper fix. what's wrong here, when you click the log link then API endpoint authorization does not happen?
> 
> It opens a link in a new tab trying to fetch a file, but since JWT token is not passed in HTTP header, the request is not authorized

JWT also set in cookies, and API in this case should also recognise it. @tranchitella @alfrunes please confirm

2024-03-04 12:42 UTC, alfrunes commented
> JWT also set in cookies, and API in this case should also recognise it. @tranchitella @alfrunes please confirm

Correct, the backend uses the `JWT` cookie as the session token.

2024-03-04 12:50 UTC, mineralsfree commented
Then it seems the problem is that the cookie is not saved/sent on frontend, I cannot see anything similar to JWT or other auth cookie in dev tools after I log in. @aleksandrychev @alfrunes @tranchitella

2024-03-04 13:14 UTC, aleksandrychev commented
yes, right. now UI moves token from cookies to localStorage.  @mineralsfree you can use 
```cookies.set('JWT', token, { path: '/', secure: true, sameSite: 'strict', maxAge: 5 });``` before downloading, as we do for other downloads. maxAge will set cookies life time for a 5 seconds.

2024-03-05 08:55 UTC, aleksandrychev requested changes

2024-03-05 08:55 UTC, aleksandrychev commented on src/js/components/devices/device-details/deployments.js
> +  const columns = [
no need to move columns inside the history component, you can pass token to the component

```
{columns.map(({ key, Component }) => (
                <TableCell key={`${item.id}-${key}`}>
                  <Component deviceDeployment={item} token={token} />
                </TableCell>
              ))}
```

and get it later 
```Component: ({ deviceDeployment: { id, log, deviceId }, token }) =>```

2024-03-05 08:55 UTC, aleksandrychev commented on src/js/components/devices/device-details/deployments.js
> +  const { token } = useSelector(getCurrentSession);
please use getToken() from auth

2024-03-05 08:55 UTC, aleksandrychev commented on src/js/components/devices/device-details/deployments.js
> +            onClick={() =>
there is createDownload function in the helpers.js that makes cookie set

```
export const createDownload = (target, filename, token) => {
  let link = document.createElement('a');
  link.setAttribute('href', target);
  link.setAttribute('download', filename);
  link.style.display = 'none';
  document.body.appendChild(link);
  cookies.set('JWT', token, { path: '/', secure: true, sameSite: 'strict', maxAge: 5 });
  link.click();
  document.body.removeChild(link);
};
```

2024-03-05 13:51 UTC, aleksandrychev commented
@mineralsfree please update snapshot and then good to go

2024-03-07 17:25 UTC, aleksandrychev approved these changes

2024-03-07 17:25 UTC, aleksandrychev commented
@tranchitella backport?

2024-03-10 19:29 UTC, tranchitella commented
> @tranchitella backport?

no need to backport this fix.

2024-03-10 19:29 UTC, tranchitella approved these changes

2024-03-11 08:02 UTC, merged